In [14]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.models import Sequential, save_model, load_model

In [22]:
# Загрузка данных
bot_data = pd.read_csv('bot2.csv')
user_data = pd.read_csv('user2.csv')

print(user_data)


# Удаление ненужных столбцов
bot_data = bot_data.drop(['id', 'user_id', 'hit_x', 'hit_y', 'min_light', 'max_light'], axis=1)
user_data = user_data.drop(['id', 'user_id', 'hit_x', 'hit_y', 'min_light', 'max_light'], axis=1)

bot_data['label'] = 1
user_data['label'] = 0

# Объединение данных
data = pd.concat([bot_data, user_data])

print(data)

# Разделение на признаки (X) и метки (y)
X = data.drop(['label'], axis=1).astype(float)
y = data['label'].astype(int)

# Нормализация признаков
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Разделение на обучающий и тестовый наборы
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

      id  user_id  max_device_offs  min_device_offs  max_dev_acceleration  \
0    205        1         0.235031         0.000000             19.703700   
1    206        1         0.000000         0.000000              0.000000   
2    207        1         0.000000         0.000000              0.000000   
3    208        1         0.740928         0.000000             10.834556   
4    209        1         0.339602         0.000000              7.187080   
..   ...      ...              ...              ...                   ...   
224  429        1         0.006627         0.000351              0.579548   
225  430        1         0.001944         0.000927              0.231436   
226  431        1         0.001336         0.000235              0.472569   
227  432        1         0.001436         0.000607              0.522172   
228  433        1         0.000811         0.000811              0.142184   

     min_dev_acceleration  min_light  max_light  hit_y  hit_x  
0          

In [23]:
# Ваш код для загрузки, удаления ненужных столбцов и добавления меток

# Преобразование данных в трехмерный массив (образцы, временные шаги, признаки)
X_train_reshaped = X_train[:, np.newaxis, :]
X_test_reshaped = X_test[:, np.newaxis, :]

# Построение и обучение модели LSTM
model = Sequential()
model.add(LSTM(64, input_shape=(1, X_train.shape[1])))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X_train_reshaped, y_train, epochs=10, batch_size=32, validation_data=(X_test_reshaped, y_test))

# Оценка модели
loss, accuracy = model.evaluate(X_test_reshaped, y_test)
print(f"Test loss: {loss:.4f}, Test accuracy: {accuracy:.4f}")

Epoch 1/10
8/8 [==============================] - 4s 105ms/step - loss: 0.6841 - accuracy: 0.6104 - val_loss: 0.6741 - val_accuracy: 0.6379
Epoch 2/10
8/8 [==============================] - 0s 10ms/step - loss: 0.6691 - accuracy: 0.7143 - val_loss: 0.6588 - val_accuracy: 0.6897
Epoch 3/10
8/8 [==============================] - 0s 10ms/step - loss: 0.6553 - accuracy: 0.7316 - val_loss: 0.6446 - val_accuracy: 0.6897
Epoch 4/10
8/8 [==============================] - 0s 9ms/step - loss: 0.6417 - accuracy: 0.7403 - val_loss: 0.6305 - val_accuracy: 0.6897
Epoch 5/10
8/8 [==============================] - 0s 10ms/step - loss: 0.6275 - accuracy: 0.7662 - val_loss: 0.6160 - val_accuracy: 0.8103
Epoch 6/10
8/8 [==============================] - 0s 10ms/step - loss: 0.6133 - accuracy: 0.7879 - val_loss: 0.6012 - val_accuracy: 0.8103
Epoch 7/10
8/8 [==============================] - 0s 9ms/step - loss: 0.5996 - accuracy: 0.7879 - val_loss: 0.5866 - val_accuracy: 0.8103
Epoch 8/10
8/8 [============

In [24]:
loss, accuracy = model.evaluate(X_test_reshaped, y_test)
print(X_test_reshaped)
print(f"Test loss: {loss:.4f}, Test accuracy: {accuracy:.4f}")


2/2 [==============================] - 0s 5ms/step - loss: 0.5443 - accuracy: 0.8103
[[[-0.72106975 -0.11846978 -0.50122022 -0.11846979]]

 [[-0.72178435 -0.11846978 -0.50023571 -0.11846979]]

 [[-0.7222657  -0.11846978 -0.49106636 -0.11846979]]

 [[-0.72116744 -0.11846978 -0.4898008  -0.11846979]]

 [[ 0.79030939 -0.11846977  0.65207923 -0.11846978]]

 [[-0.72118482 -0.11846978 -0.49937249 -0.11846979]]

 [[-0.72132167 -0.11846978 -0.49113514 -0.11846979]]

 [[-0.7213914  -0.11846978 -0.47285757 -0.11846979]]

 [[-0.7226606  -0.11846978 -0.50772795 -0.11846979]]

 [[ 0.09363499 -0.11846977 -0.48052938 -0.11846978]]

 [[-0.72189304 -0.11846978 -0.49573748 -0.11846979]]

 [[-0.72140792 -0.11846978 -0.49889348 -0.11846979]]

 [[-0.7226606   8.44097151 -0.50772795  8.44097151]]

 [[-0.71888328 -0.11846978 -0.49890869 -0.11846979]]

 [[-0.72143501 -0.11846978 -0.50013797 -0.11846979]]

 [[-0.72190307 -0.11846978 -0.49641741 -0.11846979]]

 [[-0.72171811 -0.11846978 -0.50366813 -0.11846979]

In [25]:
save_model(model, 'model.model')

INFO:tensorflow:Assets written to: model.model\assets


INFO:tensorflow:Assets written to: model.model\assets


In [17]:
model_loaded = load_model('model.model')

In [18]:
loss, accuracy = model_loaded.evaluate(X_test_reshaped, y_test)

2/2 [==============================] - 1s 5ms/step - loss: 0.4381 - accuracy: 1.0000


In [27]:
# Загрузка данных
bot_data = pd.read_csv('bot2.csv')
user_data = pd.read_csv('user3.csv')

# Удаление ненужных столбцов
bot_data = bot_data.drop(['id', 'user_id', 'hit_x', 'hit_y', 'min_light', 'max_light'], axis=1)
user_data = user_data.drop(['id', 'user_id', 'hit_x', 'hit_y', 'min_light', 'max_light'], axis=1)

bot_data['label'] = 1
user_data['label'] = 0

# Объединение данных
data = pd.concat([bot_data, user_data])

print(data)

X = data.drop(['label'], axis=1).astype(float)
y = data['label'].astype(int)

# Нормализация признаков
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Преобразование данных в трехмерный массив (образцы, временные шаги, признаки)
X_test_reshaped = X_scaled[:, np.newaxis, :]

# Оценка модели
loss, accuracy = model.evaluate(X_test_reshaped, y)
print(f"Test loss: {loss:.4f}, Test accuracy: {accuracy:.4f}")


    max_device_offs  min_device_offs  max_dev_acceleration  \
0          0.002344         0.000382              0.867096   
1          0.001408         0.000091              0.621519   
2          0.001378         0.000791              0.711498   
3          0.001079         0.000584              0.426665   
4          0.001480         0.000301              0.555638   
..              ...              ...                   ...   
36         0.848272         0.007994             20.826056   
37         0.278899         0.278899              9.229548   
38         1.296899         0.423823             15.752228   
39         0.947388         0.330559             10.311467   
40         0.840926         0.419930             29.544611   

    min_dev_acceleration  label  
0               0.064040      1  
1               0.065879      1  
2               0.174856      1  
3               0.159103      1  
4               0.087164      1  
..                   ...    ...  
36              1